### PR TITLE
Shorter version of left header on signage

### PR DESCRIPTION
**Pull request by Starshine**
short enough to play basketball in jr high 
potentially make vendors w square logos happier

### CODE REVIEW

**Comment by kylerisse** [comment]
Hi @Starshine thank you for the contribution. As discussed, could you please change the dimensions to 360x170? That was it matches the traditional size, captured here: https://github.com/socallinuxexpo/scale-signs/commit/331d6fa1901f1352a6377b4221e709c30542c8de#diff-206ad6030601dd7e13bdbc8e0761f53c076ee48d8d3df5ae44d1c5284419ca46

**Comment by Starshine** [comment]
Yep, can do.

**Comment by Starshine** [comment]
please pay attention to the ignorable fax voice 
some messages may have changed ;p
(size does matter)

**Comment by kylerisse** [comment]
lgtm, thank you @Starshine

**Comment by sarcasticadmin** [comment]
:shipit:

**Pull request merged**
