### PR TITLE
remove virtualization

### PR DESCRIPTION
**Pull request by irabinovitch**
s/and Virtualization//

### CODE REVIEW

**Comment by kylerisse** [comment]
Hope you don't mind me pushing into this PR. This thing is kind of convoluted. The key in the hashmap has to match what Drupal feeds us minus spaces in the topics tag from http://www.socallinuxexpo.org/scale/17x/sign.xml.

If the public site will continue to use "Container and Virtualization" as the topic tag then the state of this branch is the fix. If you wanted to change it on the Drupal side also, which would affect the xml being ingested, then I can update it here to match (3 places, scroll.php, room.php, and style.css). @irabinovitch please review the screenshot and if good we can approve, assuming no changes on the Drupal side to this topic.

image

**Comment by irabinovitch** [comment]
@kylerisse makes sense. thats why I asked for a review. thanks.

**Comment by irabinovitch** [comment]
@kylerisse I may try for a change on the drupal side in the next day or so and if so come back here to update the map if needed.

**Comment by kylerisse** [comment]
Went ahead and pre-populated so it's one less thing to deal with. Realized it doesn't hurt to support both. Thanks @irabinovitch!

**Pull request merged**
